name: deeptext_lm_pretrain
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1
  - numpy=1.19.2
  - pip=20.3.3
  - python=3.7.9
  - pytorch=1.7.0
  - pip:
    - click
    - pyyaml
    - tensorboard
    - texttable
    - transformers
    - sentencepiece
